### ISSUE TITLE
App password invalidated if IMAP auth server not accessible

### ISSUE THREAD

**Issue by duritong** [nextcloud/user_external#1]
### Affected apps

imap backend

### Steps to reproduce

This is a copy over from https://github.com/nextcloud/server/issues/12703

On a nextcloud 14.0.4 installation:

Everytime there seems to be a hickup with the imap server all the app passwords are lost.

This is especially bad, as the nexctloud client retries to auth with the lost app password, where nextcloud then tries to re-auth at the imap server, which might get you eventually locked, because of too many wrong login attempts.

@ChristophWurst mentioned:

> On a second thought I'm wondering if it shouldn't be the IMAP user back-end that can store known 
> users and handle these cases properly with an exception that makes the instance inaccessible in 
> general as long as the user back-end is unavailable.
>
> If the user back-end tells Nextcloud "this password is wrong" then Nextcloud will do its "wrong 
> password" procedure.

**Comment by ChristophWurst** [comment]
Probably resolved as described in https://github.com/nextcloud/server/issues/12703#issuecomment-447837015.

**Comment by duritong** [comment]
I am still waiting for a hickup with the imap server, but running on 15.0.2 now ;)

**Comment by violoncelloCH** [comment]
closing this... if it happens again for you, we can reopen the issue
