### ISSUE TITLE
Feature request imap groups via domain-part

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_external#10]
I've configured the external user login via imap. It would be great if it's possible to create a group and automatically add new users which a given domain-part to a group.

by @RubenKelevra from https://github.com/nextcloud/server/issues/1253

**Comment by violoncelloCH** [comment]
related to #10

**Comment by lavdnone** [comment]
nextcloud/user_external https://github.com/nextcloud/user_external/pull/65
