### ISSUE TITLE
Basic Auth User Login is Case Sensitive

### ISSUE THREAD

**Issue by Thommy1231** [nextcloud/user_external#107]
### Steps to reproduce
1. Use User_External with Basic Auth
2. Use a username with Upper Case letter (f.e. Thommy1231)
3. Log in with lower case username (thommy1231)

### Expected behaviour
Expected behaviour or wish: login successful

### Actual behaviour
Login failed

### Affected Authentication backend
Basic Auth

### Server configuration

**User External App version:** (see Nextcloud apps page)
0.7.0
**Operating system:**
Ubuntu Server 18.04

**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.03
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Comment by nerdmaennchen** [comment]
Hello and thank you for contributing!

Honestly, I don't think what you described is a buggy behavior.

BasicAuth is not in charge of the actual authentication (it delegates it) and therefore the behavior you desire should not be implemented inside BasicAuth but in the underlying authentication mechanism.
