### ISSUE TITLE
Internal Server Error on initial IMAP login

### ISSUE THREAD

**Issue by markc** [nextcloud/user_external#113]
However the account seems to be created and a subsequent login attempt succeeds. NC 17.0.1 with updated apps. Nothing seems to be obvious in the attached data/nextcloud.log snippet but nginx reported this error around about the same time...

`2019/12/19 15:00:20 [crit] 20073#20073: *3354921 connect() to unix:/home/u/XXXXXXXXX.cloud/var/run/fpm.sock failed (2: No such file or directory) while connecting to upstream, client: XXX.18.39.203, server: XXXXXXXXX.cloud, request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0", upstream: "fastcgi://unix:/home/u/XXXXXXXXX.cloud/var/run/fpm.sock:", host: "XXXXXXXXX.cloud"`

![20191219_Nextcloud_IMAP-Login_Error](https://user-images.githubusercontent.com/8134/71150298-dc90fd00-227c-11ea-9410-6f9119735a0d.jpg)

[nextcloud-imap-login-error.json.txt](https://github.com/nextcloud/user_external/files/3982007/nextcloud-imap-login-error.json.txt)

**Comment by violoncelloCH** [comment]
Hi @markc 
can you reproduce this error?
I'd need some further information to try to reproduce your issue... could you please fill in the issue template?
Thanks!

**Comment by violoncelloCH** [comment]
will reopen this if more information is provided...
