### ISSUE TITLE
novalidate-cert

### ISSUE THREAD

**Issue by ThorstenUm** [nextcloud/user_external#115]
Hello,
In Nextcloud i have the problem, that the user_external tool can not connect to imap server. he can not validate the certificat. When i testing
imap_open("{127.0.0.1:143/imap/tls/novalidate-cert}", "...
then i have good connection. I have lets encript certifikate. Non self signed...
Can anyone help me.

**Comment by violoncelloCH** [comment]
If you're using a Let's encrypt certificate for your mail server, you should use your mail server's domain rather than 127.0.0.1 or localhost so the certificate matches the domain name and is therefore accepted as valid...
