### ISSUE TITLE
change password in user menu

### ISSUE THREAD

**Issue by benks-io** [nextcloud/user_external#123]
**Is your feature request related to a problem? Please describe.**
It would be great if changing the password for the imap account also worked within Nextcloud.

**Describe the solution you'd like**
Have a form at the same menu like a native Nextcloud user.

**Describe alternatives you've considered**
This may also be a feature request for Nextcloud mail app.

**Comment by violoncelloCH** [comment]
hmm, is there a standard way (API) to change a Password on an IMAP server? Otherwise I guess this is impossible to implement
even though I get the point of this PR, this seems a little bit out of scope for this app (at least to me)...

**Comment by benks-io** [comment]
Yes, I guess now it's out of scope, too and close the ticket.
/close

**Comment by violoncelloCH** [comment]
yes, it's not something that could be done from user_external
