### ISSUE TITLE
OC_User_IMAP supporting only TLSv1

### ISSUE THREAD

**Issue by lsbbs** [nextcloud/user_external#13]
### Affected apps
user_external
### Steps to reproduce
1.
    Use OC_User_IMAP for authentication
    {imapserver:143/imap/tls/readonly}
2. Disable TLSv1 on the IMAP server remaining TLSv1.1 and TLSv1.2

See closed issue for Nectcloud nextcloud/server#10328

**Comment by violoncelloCH** [comment]
related to #44
