### ISSUE TITLE
Cant download user_external-0.9.1.tar.gz

### ISSUE THREAD

**Issue by pepo-ec** [nextcloud/user_external#146]
Hi friends... when I try to download user_external-0.9.1.tar.gz I have an error: SignatureDoesNotMatch

**Comment by violoncelloCH** [comment]
where are you  trying to download it from, and where does this error pop up? could you please give some details?

**Comment by pepo-ec** [comment]
Now is ok... Before when I tried to download (from realeases) it have an error about signature "SignatureDoesNotMatch"

**Comment by violoncelloCH** [comment]
okay, so let's close this...
