### ISSUE TITLE
Domain isn't stripped from username

### ISSUE THREAD

**Issue by it-management** [nextcloud/user_external#155]
If $domain isn't specified for a backend, username is always the same as uid and no domain stripping is proceeded.
See lines 64-80 in current version of imap.php.

I need to let users with more domains to login (they always have a unique user name) but with this bug is domain always part of username.

**Comment by violoncelloCH** [comment]
this is by design: if you strip the domain, you (as the admin) should know what (domain) you're striping, you shouldn't be striping everything...
for your usecase I'd suggest to define multiple IMAP backends (one for each domain)
