### ISSUE TITLE
IMAP Authentication using TLS on port 993 is broken

### ISSUE THREAD

**Issue by standardrat** [nextcloud/user_external#163]
### Steps to reproduce
1. Setup an IMAP server using TLS on port 993
2. Set up config.php with imap support with TLS
```
  'user_backends' => array(
    array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            'imap.server.co', 993, 'tls', 'server.co', true, false
        ),
    ),
),
```
3. Attempt to log in to nextcloud

### Expected behaviour
Log in should complete successfully

### Actual behaviour
Login is timing out. 

### Affected Authentication backend
IMAP using TLS

### Server configuration
version 20.0.2
Fresh install

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
`ERROR: Could not connect to imap server via curl: Operation timed out`
```
</details>

Found the problem and fix:
https://github.com/nextcloud/user_external/blob/8a4e57bfcddeee51448edb5233d6d58cda7ca68c/lib/imap.php#L88
It only sets the protocol to imaps for ssl, not tls. Changing the line to the following fixes the issue:
`$protocol = ($this->sslmode === "ssl" || $this->sslmode === "tls") ? "imaps" : "imap";`

Seems loosely related to #140

**Comment by Thomb89** [comment]
we got the same problem with the following configuration

```
'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => 'imap.example.com',
        1 => 993,
        2 => 'ssl',
        3 => 'example.com',
        4 => true,
        5 => false,
      ),
    ),
  ),
```

**Comment by mmccarn** [comment]
I can also login with 'tls' enabled by changing the port from 993 to 143 - although in view of my next comment that may simply mean I'm logging in with no encryption at all...

The current code sets two options  for curl when sslmode is 'tls':

```
if ($this->sslmode === 'tls') {
                        curl_setopt($ch, CURLOPT_USE_SSL, CURLUSESSL_ALL);
                }
```
I cannot find either of these options in the [PHP documentation for curl-setopt](https://www.php.net/manual/en/function.curl-setopt.php)

This (non php.net) webpage says that CURLOPT_USE_SSL was added in php7 v7.11: https://curl.se/libcurl/c/CURLOPT_USE_SSL.html (this doesn't do much for me on Ubuntu LTS 18.04.5 LTS running php 7.4...)

The 'debug' logging for user_external should generate a log entry showing the actual connection encryption that was applied...

**Comment by standardrat** [comment]
Finally got back to look into this more. 

I verified in the IMAP server logs that when setting the SSL mode to 'ssl', it still uses TLS 1.3 over SSL. The 'tls' setting seems to only be for STARTTLS connections, which start out unencrypted, over port 143. 

It seems I had opened this issue due to a misunderstanding, and am therefore closing it.
