### ISSUE TITLE
Inconsistent Usersearch behaviour local vs external Users

### ISSUE THREAD

**Issue by lephisto** [nextcloud/user_external#17]
### Affected apps
user_external 
### Steps to reproduce
1. Create a Local user with a name
2. Create an external user by logging in one time, eg. with IMAP
3. Search for a part of the Name.

### Expected behaviour
When Searching for "Doe" I would expect to find all users called John Doe using the User Management Tool of NC, no matter it's a local or external User.

### Actual behaviour
A Search Query "Doe" won't find John Doe, if he's an external User. If he's a local User the Match will be fuzzy, eg. $search . "%" vs "%" . $search . "%"

### Server configuration

**Operating system**:

Ubuntu 16.04

**Web server:**

Apache 2.4

**Database:**

Mysql 

**PHP version:**

5.6.35

**Server version:** (see your admin page)

10.0.6, but reproduceable with 12.0.7, too

**Updated from an older installed version or fresh install:**

Updated since OC

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

IMAP

### Client configuration
**Browser:**

various (Chromium, Safari etc)

**Operating system:**

Linux, OSX etc

I made a pull Request to fix this behaviour, please check nextcloud/apps#51

**Comment by violoncelloCH** [comment]
could you reopen your PR here at the new Repo?

**Comment by lephisto** [comment]
I can't believe this is still open.

**Comment by violoncelloCH** [comment]
Unfortunately PRs can't be moved from the old repo and I wanted to give you the chance to open a new PR here? Do you wan't to do this or should I apply the fix?

**Comment by lephisto** [comment]
This is fixed with #74 (where the issue was slightly different) and behaving like it should. I close this.

**Comment by violoncelloCH** [comment]
ahh, cool! that's even better :) thanks!

**Comment by jollysolutions** [comment]
This doesn't work for me. We do not have display names but when on the user page and filter by part of an email address no user shows unless it matches the beginning of the email address. 

e.g.

users email is user@test.example.com

if you type test no user shows only ig=f you type user does it show

**Comment by violoncelloCH** [comment]
@jollysolutions which versions of user_external and nextcloud do you use?
are you talking about the sharing user lookup or the admin/users search?
