### ISSUE TITLE
If I deactivate the addon user_external. Now four times a second an error appear in log

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/user_external#170]
### Steps to reproduce
1. Deactivate User External
2. enter /index.php/settings/admin/logging
3. see appearing many same errors

### Expected behaviour
no error

### Actual behaviour
four times a second this message appear:
`{"reqId":"YCvlzNYLYmKrKK82ZzmvZgAAAAU","level":3,"time":"2021-02-16T16:33:32+01:00","remoteAddr":"xx.xx.xx.xx","user":"xxxx","app":"core","method":"GET","url":"/index.php/apps/logreader/poll?lastReqId=YCvlzPBJ-F6UxeziG%40GcWAAAAAw","message":"User backend OC_User_IMAP not found.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"20.0.6.1","id":"602be5cc9db4a"}`

### Affected Authentication backend
IMAP was used for tests

### Server configuration

**User External App version:** 1.0

**Operating system:** unknown

**Web server:** appache

**Database:** 10.3.27-MariaDB

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here.
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by violoncelloCH** [comment]
well, from within your `config.php` you tell Nextcloud to call the class `OC_User_IMAP` (at least I'm guessing that as you didn't fill in the issue template) so if you don't remove (or comment out) that section but just disable the app, Nextcloud will still try to use that class even though it isn't there anymore

**Comment by Mannshoch** [comment]
Important detail. Thanks for this. Would you think there is may a need for an enhancement request for the log. So there do appear such kind of information?
e.g. `"User backend OC_User_IMAP` `mentioned in config.php` `not found."`

**Comment by violoncelloCH** [comment]
Well of course that could make sense, but I don't know if it's possible. This error is generated by Nextcloud server and not the user_external app. To me it looks like a pretty generic error message, so not sure if that could be easily adapted to include a phrasing as in your example.
