### ISSUE TITLE
Compatibility with NC21

### ISSUE THREAD

**Issue by Glandos** [nextcloud/user_external#171]
**Is your feature request related to a problem? Please describe.**
Nextcloud 21 is released. Could we set max version to 21 to make it work? Or is there anything that we can do?

**Comment by Glandos** [comment]
After clearing the cache and setting max version to 21, it seems to work perfectly for IMAP.

**Comment by violoncelloCH** [comment]
Please note that there were some breaking changes introduced in NC 21 which affect the user_external app (#165). So I can't recommend updating to NC21 yet if you rely on user_external. 

> After clearing the cache and setting max version to 21, it seems to work perfectly for IMAP.

Interesting to hear that it seems to work for you. Did you try logging in with a new user?

**Comment by Glandos** [comment]
No, I am a single user on this instance, sorry

**Comment by miqros** [comment]
> 
> 
> After clearing the cache and setting max version to 21, it seems to work perfectly for IMAP.

Hi. Could you please tell us, what exactly you did for get app working?

**Comment by 2xsaiko** [comment]
It seems to work for me too. After the initial update I couldn't log back in with my external user, then I enabled the user_external app through the web interface (which also didn't seem to work), then disabled and re-enabled it via these commands:

    occ app:disable user_external
    occ app:enable user_external

Not sure why that got it to work, but I'll take it.

**Comment by cscognamiglio** [comment]
I just had this issue because I (hastily) upgraded to NextCloud 21. I am using docker.
I solved by changing max-version in appinfo/info.xml to 21 like so:

<nextcloud min-version="17" max-version="21" />

I am using the http base authentication and it seems to work, my instance has several users, so I am not sure if this will be enough also for the other types of authentication.
I had to manually install it in the apps/ folder though and after the modification above I could enable it with no issue.

**Comment by brknkfr** [comment]
This pull request seems to fix it: https://github.com/nextcloud/user_external/pull/173

**Comment by jrd** [comment]
The patch in the merge request works.

**Comment by almereyda** [comment]
Did you try the patch on an existing installation, or on a new one?

I can confirm that it works for the first case, but am unsure if the way it is implemented respects migrations for what they are.

Would you have any second opinions on my comment in the PR https://github.com/nextcloud/user_external/pull/173#issuecomment-812774406 ?

**Comment by jrd** [comment]
I tried on a new one.

**Comment by brknkfr** [comment]
> Did you try the patch on an existing installation, or on a new one?
> 
I tried on a fresh/new installation and on an old one.

**Comment by violoncelloCH** [comment]
new release is out!
thanks for the PR @hlnd
