### ISSUE TITLE
Update to NextCloud 22.1.1 needed

### ISSUE THREAD

**Issue by arsounet** [nextcloud/user_external#182]
The External user authentication needs to be updated for NextCloud 22.1.1.

Maybe it's not need in code but give a look at the NextCloud support.

![image](https://user-images.githubusercontent.com/758451/131492912-f26c0998-f723-4d21-9001-5ee0af7c885d.png)

Big thanks

**Comment by violoncelloCH** [comment]
closing as duplicate of #179
