### ISSUE TITLE
Internal Server Error during IMAP-login with PGSQL

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/user_external#20]
Hello folks,
trying to authenticate an NC-user via IMAP4, fails with the following error:
```
Internal` Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: 70.191.2.004
Request ID: Xn559eWohGNv41PyObSB
```
The logfile points to:
https://github.com/nextcloud/apps/blob/f8fb4d98464254c037b330d4a17c9851b7bee823/user_external/lib/imap.php#L55-L59
             
where quotation of string-expressions in plain SQL seems to be the problem: SQL-strings with dbl-quotes aren't allowed for postgres. Attached patch fixes the problem and hands-off backend-aware quoting to the prep.-statement-executor.
```
 $result = OC_DB::executeAudited(
                 SELECT `userid` FROM `*PREFIX*preferences` WHERE `appid`=? AND `configkey`=? AND `configvalue`=?',
                 array('settings','email',$uid)
                );
```
[patch_user_external_pgsql.diff.txt](https://github.com/nextcloud/apps/files/1642764/patch_user_external_pgsql.diff.txt)
++umgfoin.

**Comment by violoncelloCH** [comment]
Seems to be nextcloud/apps#47 which was merged; otherwise please reopen the issue.
