### ISSUE TITLE
Configuratin per GUI

### ISSUE THREAD

**Issue by ThePatzen** [nextcloud/user_external#201]
Hallo,

es wäre Spitze, wenn die Backend-Konfiguration per GUI erfolgen könnte. / Wenn man keine Änderung an der Config.php vornehmen müsste!

MfG

**Comment by jensb** [comment]
I second this, strongly.
Many cloud providers offer Nextcloud hosting and you can install apps, but cannot access config.php.

Thanks!

**Comment by jensb** [comment]
Also, this is a duplicate of #28

**Comment by violoncelloCH** [comment]
yes, thanks for the input - closing this as a duplicate of #28
