### ISSUE TITLE
more than one domain should be allowed to be configured as valid imap auth domain in config.php

### ISSUE THREAD

**Issue by bjoern86** [nextcloud/user_external#21]
more than one domain should be allowed to be configured as valid imap auth domain in config.php:

'user_backends' => array(
    array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            '{127.0.0.1:143/imap/readonly}', 'example1.com, example2.com, example3.com'
        ),
    ),
),

alternatively:

'user_backends' => array(
    array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            '{127.0.0.1:143/imap/readonly}',
            'example1.com',
            'example2.com',
            'example3.com'
        ),
    ),
),

**Comment by violoncelloCH** [comment]
I want to point out, that it's already possible to register multiple backends for this purpose... (Just add multiple IMAP auth backends to the config.php with each the same config except the domain...)
Starting from v0.6.3 it's also possible to configure the striping of the domain part for the username optionally...

**Comment by unclesamwk** [comment]
Can you please give us an example?
I want to add more imapserver with different domains

**Comment by violoncelloCH** [comment]
that'd be just something like:
```
'user_backends' => array(
    array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            'imap.example.com', 993, 'ssl', 'example.com', true, false
        ),
    ),
   array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            'imap.example.com', 993, 'ssl', 'yourmaildomain.com', true, false
        ),
    ),
),
```

**Comment by unclesamwk** [comment]
thx, it works very nice

**Comment by ychaouche** [comment]
I would close this issue

**Comment by violoncelloCH** [comment]
yes, I agree @ychaouche 
this use case can be easily achieved by configuring multiple backends as stated above...
