### ISSUE TITLE
Users unable to login to Nextcloud V25 via IMAP

### ISSUE THREAD

**Issue by brad2014** [nextcloud/user_external#211]
If an installation is upgraded to NC v25, users who are authenticated via user_external (e.g. IMAP) will be locked out, because the user_external app, required for logging in, will be silently and automatically disabled.

A consequence of issue raised in #210 .

Workaround: The app can be reenabled manually using nextcloud/occ (run as the nextcloud owner, e.g. apache)

% occ app:enable user_external --force

**Comment by violoncelloCH** [comment]
hey, sorry for this... as you have stated, onne can manually re-enable the app...

anyways, I've just released a new version of the app, compatible to NC25...

**Comment by prismopensource** [comment]
Thanks! Maybe you could add some extra developers to this project to help expedite these changes?

**Comment by violoncelloCH** [comment]
if anyone wants to help out, feel free to step up and do so :)

just to clarify: I'm not part of Nextcloud GmbH - I'm maintaining this app in my spare time...
