### ISSUE TITLE
Nextcloud advertises updates to v3.1, but shows no changelog. Where is the v3.1 release?

### ISSUE THREAD

**Issue by jensb** [nextcloud/user_external#216]
### Steps to reproduce
1. Open Nextcloud with an old version of user_external installed
2. Go to apps menu as admin
3. user_external upgrade to v3.1 is advertised

### Expected behaviour
There should be a changelog and when clicking the link to "Visit Website" or "View in Store" the Github or Nextcloud app site should contain the release that Nextcloud is advertising.

### Actual behaviour
No changelog (do I need to change the server config?), no release on Github, no information on the Nextcloud app site.
Before I update an app that affects every single of my users I like to review the code changes of that app.

### Affected Authentication backend
All.

### Server configuration
Not relevant.

**Comment by violoncelloCH** [comment]
hi, sorry for this - I forgot to add the changelog before the merge and release... here it is: https://github.com/nextcloud/user_external/pull/214

also the release of v3.1 should be visible here: https://apps.nextcloud.com/apps/user_external

**Comment by jensb** [comment]
Thank you!
The release was visible, but not the changelog. I hesitated upgrading a production system without knowing what changes to expect.
