### ISSUE TITLE
Can not determine user count for OCA\UserExternal\IMAP

### ISSUE THREAD

**Issue by Feciam** [nextcloud/user_external#218]
Bonjour 
c'est quoi le problème svp
![image](https://user-images.githubusercontent.com/101017509/214340212-4543b962-d38d-4edb-87d8-b6fe9d41439d.png)

**Comment by lonyai** [comment]
I have also this issue on Nextcloud v28.0.0 and user_external v3.2.0
How can I debug this "user count"?

**Comment by lonyai** [comment]
I changed back to php-8.1 and I don't see new "user count" logs. I think this issue needs a "php-8.2" flag
