### ISSUE TITLE
IMAP extension is being removed on PHP 8.1

### ISSUE THREAD

**Issue by simaoafonso-pwt** [nextcloud/user_external#219]
The IMAP extension uses `c-client`, which means it is now deprecated. What's the migration path here?

This is already a problem on Arch Linux, it's on 8.1 already.

https://archlinux.org/news/php-82-update-and-introduction-of-legacy-branch/

**Comment by simaoafonso-pwt** [comment]
Any news about this? I'm now afraid to update the Nextcloud installation, since any update can break the PHP installation.

**Comment by violoncelloCH** [comment]
Hi, thanks for the report !
This shouldn't be an issue as we are using curl for IMAP auth since v0.9.0 of this app...
