### ISSUE TITLE
Compatibility with Nextcloud 26

### ISSUE THREAD

**Issue by pieterhollander** [nextcloud/user_external#222]
At the moment, the external user authentication addon is listed as incompatible with Nextcloud 26.

**Comment by mateusmagen** [comment]
Waiting for compatibility

**Comment by nk-managedoffice** [comment]
works now for me - without any updates, 1.18.0 app version and nc26

**Comment by nk-managedoffice** [comment]
Installed a NC instance again with my Script ...

**Version**: https://download.nextcloud.com/server/releases/latest.zip (v26.0.0beta2-9-g64e24c dirty) or only 26.0.0

**Step 1**: 
user_external installation via occ command `occ app:install user_external `in the NC Admin Panel activate the app, log out as admin but! imap login does not work yet!

**Step2:**
back to the shell and start the upgrade process

`sudo -u '$customer' /usr/bin/php /var/customers/webs/'$customer'/'$domain'/updater/updater.phar --no-interaction`

**Output:**
```
Nextcloud Updater - version: v26.0.0beta2-9-g64e2e4c dirty
Current version is 26.0.0.
No update available.
Nothing to do.
```

**Step3:**
 try to login via IMAP - login and mail work without problems - same settings as 3 weeks ago.

my5cent: was no change or update - but ONLY when I start upgrade like in Step3 - I can login via "user_external" app ... no idea why

**Comment by freibadschwimmer** [comment]
user_external app does not work for me on NC26.
I had upgraded to NC26 via browser. I was able to enable user_external, but users who the users who were registered using the external authentication are not listed in the active users anylonger. I do see an increased nuber count of disabled users, but the users who registered with external authentication are not listed (there is only the count, but the list appears empty). Also, trying to log in with other/new user name for which the user_external was set up does not work.

I also tried re-initiating the upgrade from terminal, as well as `occ maintenance:repair`, but no luck.

Hence, I could not get user_external working on NC26.

**Comment by freibadschwimmer** [comment]
Now here's something odd: After reporting that the app did not work for me with NC26, I closed my computer to deal with the issue later.

Now, when I checked again, it suddenly seems to work. Not sure was miraculously fixed the problem, but the flooding logged errors stopped a few minutes after I left, the users are back listed as active users, and using IMAP login works again.
Not sure what happened meanwhile, except for maybe the cronjob must have been running (could this have done something?).

Yet, it still throws occasional errors:

```
[user_external] Error: ERROR: Could not connect to imap server via curl: 
GET /ocs/v1.php/cloud/user?format=json

[PHP] Error: Undefined array key 1 at .../nextcloud/apps/user_external/lib/IMAP.php#85
GET /ocs/v1.php/cloud/user?format=json
```

**Comment by Glandos** [comment]
Same for me, it works without any issues

**Comment by Aaron-Ritter** [comment]
If it works can you just do a final test and update the compatibility in the config file?

**Comment by Drumsk8** [comment]
I needed php occ app:enable user_external -f before it would work properly in NC26. Now I can login.

**Comment by AbLink-Sites-Internet** [comment]
I just upgraded my Nextcloud from 25.xxx to 26.0.2. External IMAP users (oc_users_ecternal database table) are not visible in user list and they can't login to Nextcloud. Only those in local (oc_users database table) can authenticate.
occ app:disable user_external and occ app:enable user_external -f don't change anything

**Comment by AbLink-Sites-Internet** [comment]
Now here's something odd, same as [freibadschwimmer](https://github.com/freibadschwimmer): After reporting that the app did not work for me with NC26, I have restarted apache to apply one PHP config change, and all users are visible now ! It makes no sense !

**Comment by Aaron-Ritter** [comment]
Hi @come-nc @skjnldsv @violoncelloCH,

As you are some of the latest committer for nextcloud/user_external I was hoping you could help us to find out what we could do to get the Compatibility with nextcloud 26 commited. As the issue is now open since soon 3 months.

Is there anything which can be done with regards to testing by side what has already been done? Really hope for your input and direction.

Thanks,
Aaron

**Comment by skjnldsv** [comment]
https://github.com/nextcloud-releases/user_external/actions/runs/5256550951

![giphy](https://github.com/nextcloud/user_external/assets/14975046/f1530e2f-b6e4-42ce-a26a-8a7b3c1f5684)

**Comment by skjnldsv** [comment]
Sorry it took so long, apps releases is overwhelming!
Please report any issues and ping me if any
