### ISSUE TITLE
Prosŏdy support?

### ISSUE THREAD

**Issue by lyn1337** [nextcloud/user_external#224]
I seem to have a problem getting the XMPP auth to work.

### Steps to reproduce
1. app:install user_external
2. setup config/config.php for Prosŏdy
3. …checked the DB table for entries

### Expected behaviour
'users_external' being populated

### Actual behaviour
nothing there

### Affected Authentication backend
XMPP

### Server configuration

**User External App version:** (see Nextcloud apps page)
3.1.0
**Operating system:**
Devuan/Linux
**Web server:**
nginx
**Database:**
my
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
23.0.12
**Updated from an older Nextcloud/ownCloud or fresh install:**
u
**Where did you install Nextcloud from:**
?
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>…</summary>

```
…
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
…
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"coC4s5Cgxd1xQKtw6cLe","level":3,"time":"2023-04-27T07:11:17+00:00","remoteAddr":"X","user":"X","app":"core","method":"POST","url":"/settings/apps/enable","message":"User backend \\OCA\\UserExternal\\XMPP not found.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"23.0.12.2","data":{"app":"core"}}
{"reqId":"lOrGaG1NvdwA28LnL8PY","level":1,"time":"2023-04-27T07:11:17+00:00","remoteAddr":"X","user":"X","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"23.0.12.2","data":[]}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
…
```
</details>

**Comment by violoncelloCH** [comment]
hi,
the users table only gets populated once the respective users log in to nextcloud

**Comment by lyn1337** [comment]
@violoncelloCH I see; still unable to login however. Might take a closer look another day.

**Comment by lyn1337** [comment]
Tested again, seems to work fine now. 👍🏻
