### ISSUE TITLE
automatic checks and builds on PRs

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/user_external#24]
can we get travis and drone CI for this Repo? (as it was in the apps repo)
What are the steps to be done?
@jancborchardt @MariusBluem Who is the right person to ask here?

**Comment by jancborchardt** [comment]
I guess the people to aks are maybe @rullzer @MorrisJobke? :)

**Comment by MorrisJobke** [comment]
> can we get travis and drone CI for this Repo? (as it was in the apps repo)

I enabled travis and drone. Please give it a try and then we can close it if it properly works 👍

**Comment by violoncelloCH** [comment]
@MorrisJobke does this work as is or do we need some config files for drone and travis in this repo? (like .drone.yml and .travis.yml ?)

**Comment by MorrisJobke** [comment]
> @MorrisJobke does this work as is or do we need some config files for drone and travis in this repo? (like .drone.yml and .travis.yml ?)

The config files are needed.

**Comment by violoncelloCH** [comment]
@MorrisJobke Okay, I've never done something like that, but I can try copy/pasting something together from the old apps repo and some other nextcloud apps. Should I do this?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Okay, I've never done something like that, but I can try copy/pasting something together from the old `apps` repo and some other nextcloud apps. Should I do this?

Yep :)

**Comment by violoncelloCH** [comment]
tests are working now (except phpunit tests)...
for the not working unit tests I created #40
