### ISSUE TITLE
Nextcloud 29 support

### ISSUE THREAD

**Issue by prismopensource** [nextcloud/user_external#246]
Since [Nextcloud 29](https://github.com/nextcloud/server/releases) is already on beta 4 at the moment we would like to request Nextcloud 29 compatibility. Releases for user_external are already far apart and there still isn't a version that supports the current Nextcloud 28 at the moment so maybe we could combine the upcoming release with Nextcloud 29 compatibility?

**Comment by VVD** [comment]
29.0.0 just released.

**Comment by prismopensource** [comment]
@violoncelloCH any idea how we can accelerate the process to get this compatible with the latest Nextcloud version? It seems your app is mentioned again in the [official documentation for Nextcloud 29](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ftp_smb_imap.html).

**Comment by joshtrichards** [comment]
Have any of you tried *force* enabling the app and ran into any problems?

**Comment by violoncelloCH** [comment]
> @violoncelloCH any idea how we can accelerate the process to get this compatible with the latest Nextcloud version? It seems your app is mentioned again in the [official documentation for Nextcloud 29](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ftp_smb_imap.html).

it now isn't anymore, see: nextcloud/documentation#11828

You can just force enable the app, there is nothing particular in this app, so as long as the few Nextcloud server APIs user_external is using did not change, this will still work. However due to my workload related to university I currently do not have the time to properly test and confidently create a release, sorry.

**Comment by Aaron-Ritter** [comment]
The problem with testing it is probably that everyone is using one maybe two of the offered mechanism. I would be curious which mechanisms are actually used.

**Comment by Glandos** [comment]
I tested Nextcloud 29.0.1 with IMAP authentication without issue.

**Comment by OutbackMatt** [comment]
I did this and it works for me with Nextcloud 29.0.2 with IMAP authentication without issue

```
-                <nextcloud min-version="25" max-version="28" />
+                <nextcloud min-version="25" max-version="29" />
```

**Comment by Aaron-Ritter** [comment]
the two recent comments are actually my point:

For one, we primarily use IMAP too, but the extension does more. My guess is that it's not known how big the user base is for each mechanism. And e.g. if the focus should be only to create a extension for IMAP instead?

**Comment by VVD** [comment]
There is no need to remove other methods. It's better to let users report errors if there are any.

**Comment by Aaron-Ritter** [comment]
> > @violoncelloCH any idea how we can accelerate the process to get this compatible with the latest Nextcloud version? It seems your app is mentioned again in the [official documentation for Nextcloud 29](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ftp_smb_imap.html).
> 
> it now isn't anymore, see: nextcloud/documentation#11828
> 
> You can just force enable the app, there is nothing particular in this app, so as long as the few Nextcloud server APIs user_external is using did not change, this will still work. However due to my workload related to university I currently do not have the time to properly test and confidently create a release, sorry.
> 
> If someone wants to help testing (and ideally write some proper automated tests for this app; something I wanted to do since a bunch of time but never found the time to), this would help of course :)

@VVD this refers to the thoughts about testing, either you know roughly the amount of usage for each mechanism or make sure to either:

a) only release and test what users are actually using, therefore remove anything you dont want to release and test

b) test only the mechanism which are "worth testing" and mark the rest as experimental which might be a risk in the end as you release something untested (especially when it comes to dependencies/vulnerabilities etc.)

c) just release with the remark that it is only community tested and hope it's all good

d) split it into individual packages for each mechanism and see which the community pushes hardest

e) test every mechanism before releasing manually or autoamted

**Comment by VVD** [comment]
IMHO:
> b) test only the mechanism which are "worth testing" and mark the rest as experimental

If there are users of other mechanisms and are ready to regularly check the functionality with new versions of the NextCloud, then remove the experimental mark.

P.S. I also only use IMAP.

**Comment by alucardx01** [comment]
I'm using SMB for auth.
