### ISSUE TITLE
error update nc15 with Latest commit c1914e8  signature data missing

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/user_external#29]
NC-14.0.4 to NC15.0.0

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- user_external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [user_external] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**Comment by violoncelloCH** [comment]
have you updated NC to 15 and then manually updated user_external with the latest master?
Note that we'll include the signature data when there is a new release (which we'll probably release via appstore - see #22). Manually updating for a stable/production server (to the latest master) is not recommended.

**Comment by violoncelloCH** [comment]
Yes, thank you for reporting; that's a known problem - see nextcloud/server#12506.
As soon as we release a new version (hopefully via appstore) or with 15.0.1, this message should go away. These signature infos are only contained in regular releases, not in master.
