### ISSUE TITLE
PHP IMAP extension deprecated

### ISSUE THREAD

**Issue by hcderaad** [nextcloud/user_external#44]
### Steps to reproduce
1. Search for php7-imap in the repo's of current distro's like openSUSE Tumbleweed
2. Lookup php-imap extension status in the formal PHP extension list

### Expected behaviour
The native PHP IMAP extension appears to be deprecated.

### Actual behaviour
The php-imap extension appears to have been abandoned by its maintainers and distro's like openSUSE no longer ship it.
https://wiki.php.net/todo/extensions#imap
https://bugzilla.opensuse.org/show_bug.cgi?id=1089061#c18

Roundcube and other mail apps appear to have moved to a custom PHP IMAP protocol implementation using the generic sockets extension.

Would it be possible to consider replacing this unmaintained dependency to a similar solution?
https://github.com/roundcube/roundcubemail/blob/82974289b98d2d00251e55f1719c4522598d7ef5/program/lib/Roundcube/rcube_imap_generic.php

### Affected Authentication backend
IMAP

### Server configuration

**Operating system**:
Several linux distro's i.e. openSUSE

**PHP version:**
>7

**Comment by violoncelloCH** [comment]
thank you for this report @hcderaad !
I get the point of your report and indeed, we could probably use roundcube's or a similar implementation to achieve this.
However for me personally, this is currently out of scope. (I'm just maintaining this app in my spare time.) But if anyone is up for an implementation, a PR is always very welcome!
cc @nextcloud/user_external

**Comment by hcderaad** [comment]
Apologies for the delayed response, many thanks for picking this up!

**Comment by wrossmann** [comment]
The IMAP extension is not deprecated, it's a core extension. I invite you to check the PHP docs or actually talk to a PHP internals person for confirmation, but as far as I am aware no one has even talked about deprecating it from PHP proper.

I cannot comment on what the OpenSUSE maintainers have been smoking that has caused them to stop packaging/shipping this extension.

**Comment by violoncelloCH** [comment]
well we're using curl for the authentication request in the mean time (#122) which seems to work well and is supported...
and sadly I wouldn't know any "php internal" or how to contact them for such information anyway...

**Comment by wrossmann** [comment]
@violoncelloCH https://www.php.net/mailing-lists.php

**Comment by violoncelloCH** [comment]
thanks @wrossmann , that's nice to know... however I see it very unrealistic to migrate back, now that we migrated first to roundcube and then to curl
