### ISSUE TITLE
Local users login with IMAP credentials is not working properly [followup]

### ISSUE THREAD

**Issue by alexanderheckel** [nextcloud/user_external#61]
Followup of closed issue #3

If it is not a supported use case to overtake local nextcloud users, this is a security issue (that it's possible to access the local users files even if you get logged out after several minutes). However, you should consider fixing this in one way or the other rather than simply closing the issue.

**Comment by violoncelloCH** [comment]
see https://github.com/nextcloud/user_external/issues/3#issuecomment-476578711
