### ISSUE TITLE
Errors for undefined variable "groups" in imap.php

### ISSUE THREAD

**Issue by alanswanson** [nextcloud/user_external#88]
### Steps to reproduce
1. Use user_external with IMAP authentication and no domain in username.

### Expected behaviour
No errors.

### Actual behaviour
Nextcloud logging the following error on every IMAP password check;

> _Undefined variable: groups at /var/www/localhost/htdocs/cloud/apps/user_external/lib/imap.php#101_

In **_lib/imap.php_** for usernames without domains the groups array/variable is not setup at `($this->groupDomain && $pieces[1]) { $groups[] = $pieces[1]; }` and hence `$this->storeUser($uid, $groups);` needs groups previously defined to null or guarded.

### Affected Authentication backend
IMAP

### Server configuration

**User External App version:** 0.6.3 plus pull #83 

**Operating system:** Gentoo

**Web server:** Cherokee

**Database:** MariaDB

**PHP version:** 7.1.30

**Nextcloud version:** 15.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Source

**Comment by violoncelloCH** [comment]
thank you for reporting @alanswanson 
as you've already pointed out the lines where this is coming from: would you be willing to create a PR for this?

**Comment by realizelol** [comment]
please have a look here:
https://github.com/nextcloud/user_external/issues/56

best regards
realizelol

**Comment by realizelol** [comment]
have a look at #56

**Comment by violoncelloCH** [comment]
@realizelol that's something different....

**Comment by alanswanson** [comment]
The fix in https://github.com/nextcloud/user_external/issues/56#issuecomment-502492778 to _apps/user_external/lib/imap.php_ resolved my log errors. (Though I tidied the the curly bracket formatting and spacing.)

**Comment by violoncelloCH** [comment]
okay I see that was discussed there later as well, but was not part of the original issue description :)
