### ISSUE TITLE
External OAuth authentication (OpenStreetMap)

### ISSUE THREAD

**Issue by don-vip** [nextcloud/user_external#89]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to login to a NextCloud instance using an OpenStreetMap (OSM) account. NextCloud server supports OAuth 1.0 but it seems limited to the External Storage feature (Dropbox, Google Drive...).

**Describe the solution you'd like**
Support OAuth 1.0 as a possible external authentication mechanism, with a predefined entry to login with an OSM account.

**Additional context**
OSM documentation: https://wiki.openstreetmap.org/wiki/OAuth

**Comment by violoncelloCH** [comment]
I'm not sure if I completely get your point...
This is the user_external app allowing you to authenticate against said protocols in a very basic, rudimentary way... 
for OAuth you're most probably better of with https://github.com/zorn-v/nextcloud-social-login
might this work for your use case?

**Comment by don-vip** [comment]
Hello,
I'm new to NextCloud, so I probably chose the wrong repository.
It seems a lot easier to create a new OAuth provider there, thanks a lot for the link!

**Comment by violoncelloCH** [comment]
no problem, you're welcome :)
yeah I guess that's the right app for your use case...
