### ISSUE TITLE
Why should i update from 0.6.3 to 0.6.4? - Please add changelog

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/user_external#95]
Hello. :-)

Is there a security issue?
New features or just typo corrections?

Please add a (small) changelog to understand why we should update. ;-)

Thanks

**Comment by violoncelloCH** [comment]
Hey, sorry, didn't have the time for that (yeah I know, I should look for a way to automatize this)... 
Please take a look at the corresponding milestone for a list of the closed issues / merged pull request for 0.6.3 to 0.6.4...

**Comment by fanfu** [comment]
Here is the direct link: https://github.com/nextcloud/user_external/milestone/9?closed=1

**Comment by pm-pm** [comment]
Thanks for that, but this are not release notes. :-)
It is a list of completed issues. It is freak-friendly, not user-friedly.

BTW: In a release notes file the can be recommendations or other important stuff to support/advice the admin and user to do the correct thinks. ;-)


Thx.

**Comment by violoncelloCH** [comment]
take a look here: #94 I updated the description :)
