### ISSUE TITLE
Internal server error imap

### ISSUE THREAD

**Issue by wabj** [nextcloud/user_external#99]
Hello,

I'm trying to use IMAP authentication but when I add the code to the config and then reload I get an Internal Server Error and no logs. 

I've followed the manual and am running the latest version. 

Please help!

**Comment by violoncelloCH** [comment]
Hi @wabj
could you please fill in the issue tehplate? 
(there is a reason we have those; otherwise it's quite impossible to reproduce your issue without any information about your setup)

**Comment by wabj** [comment]
Apologies

**Steps to reproduce**

1. Enable External User Support
2. Edit Config with imap code
2. Reload Nextcloud home page
3. Internal Server Error page
4. remove imap code, able to login as local user

My config code with private info redacted 

<?php
$CONFIG = array (
  'instanceid' => 'redacted',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' => 
  array (
    0 => 'redacted',
  ),
  'datadirectory' => 'redacted',
  'dbtype' => 'mysql',
  'version' => '16.0.3.0',
  'overwrite.cli.url' => 'redacted',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'redacted',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'redacted',
  'dbpassword' => 'redacted',
  'installed' => true,
);
'user_backends' => array(
    array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            'outlook.office365.com', 993, null, 'redacted', true, false
        ),
    ),
),

**Comment by wabj** [comment]
Sorted it. I had the code in the wrong place!

**Comment by violoncelloCH** [comment]
cool that you figured out yourself!
yes, it needs to be inside the main $CONFIG array paranthesis...

**Comment by wabj** [comment]
So silly of me!

One thing you might be able to help with. Is there anyway that the users email address is populated in their profile using the login details from IMAP authentication?



Sent from my iPhone.

On 9 Aug 2019, at 08:57, violoncello.ch<http://violoncello.ch> <notifications@github.com<mailto:notifications@github.com>> wrote:


cool that you figured out yourself!
yes, it needs to be inside the main $CONFIG array paranthesis...

**Comment by violoncelloCH** [comment]
this is not yet implemented... see #12
